version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  mysql:
    image: mysql@5.7
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_DB: travellers
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
