version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: mysql:8.0.3

        environment:
          MYSQL_ROOT_PASSWORD: start12345
          MYSQL_DATABASE: justice
          MYSQL_USER: rowland
          MYSQL_PASSWORD: start12345

    steps:
      - checkout

      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: starting node server
          command: mkdir logs && npm run start-dev 2>&1 | tee logs/node_server.log
          background: true

      - run:
          name: storing local IP address
          command: node -p "require('ip').address()" > logs/ip.log

      - run:
          name: waiting for node server to start
          command: wget --retry-connrefused --waitretry=2 -t 5 "http://$(cat logs/ip.log):5000" > /dev/null

      - run:
          name: test
          command: npm test
