version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: mysql -h mysql-8867-0.cloudclusters.net -P 8867 -u<CHUKWUKA> -p<start12345> <Riders>
            - run: npm run createTable
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
