version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:11-alpine-ram

        environment:
          POSTGRES_DB: mjrjfmbg
          POSTGRES_PASSWORD: 8UTF9HKTaXKeDaRGVbykOgzTZ152ElB1
          POSTGRES_USER: mjrjfmbg

    steps:
      - checkout

      - run:
          # Our primary container isn't POSTGRESQL so run a sleep command until it's ready.
          name: Waiting for POSTGRESQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for POSTGRESQL && exit 1
      - run:
          name: Install POSTGRESQL CLI; Import dummy data; run an example query
          command: sudo apt-get install default-postgresql-client
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: starting node server
          command: npm run start-dev 2>&1
          background: true

      - run:
          name: test
          command: npm test
