version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: mysql:8.0.3

        environment:
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DB: travellers
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: start12345

    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test
