version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: mysql:8.0.3

        environment:
          MYSQL_USER: ubuntu
          MYSQL_DATABASE: circle_test
          MYSQL_ROOT_PASSWORD: ubuntu
          MYSQL_PASSWORD: ubuntu

    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test
