version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/mysql:latest
        environment:
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DB: travellers
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: npm install
      - run:
          name: "run tests"
          command: npm test
