version: 2.1
orbs:
  node: circleci/node@10.17.0
jobs:
  build:
    docker:
      - image: circleci/mysql@5.7
        environment:
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DB: travellers
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
